#ifndef CONFIG_H
#define CONFIG_H

#define USE_POWERBUTTON
#define USE_DISPLAY
#define USE_EEPROM
#define USE_SERIAL
#define USE_CONVERTER
#define USE_COUNTER
#define DEBUG_ENABLE

#define POWER_PIN 2
#define POWER_BUTTON 4

#define DISPLAY_BASE_PIN 10
#define DISPLAY_L_PIN  10
#define DISPLAY_C_PIN  13
#define DISPLAY_D_PIN  11
#define DISPLAY_REFRESH_MS 30
#define DISPLAY_NEW_MS 330
#define DISPLAY_POPUP  3 /* times of NEW_MS */

#define COUNTER_TRIG_PIN 3
#define COUNTER_INTR 1
#define COUNTER_FACTOR 0.00549
#define LED_PIN -1

#define CONVERTER_PWM_PIN 9
#define CONVERTER_U_PIN A6
#define CONVERTER_I_PIN A7
#define CONVERTER_SETPOINT 200
//#define CONVERTER_OPENLOOP
#define CONVERTER_CURRENT
#define CONVERTER_U_FACTOR (1.1/1024.0*(3.0*9100.0/33.0+1.0))
#define CONVERTER_I_FACTOR (1.1/1024.0*1000.0/120.5) /* 120.5 Ohm */
#define CONVERTER_MULT  2


#endif
